var Msg = {
	menu : {
		"home" : "Home",
		"config" : "Configuration",
		"community" : "Community",
		"infotrial" : "Info",
		"costi" : "Cost",
		"consumi" : "Cost/Consumption",
		"fv" : "PhotoVoltaic",
		"dispositivi" : "Appliances",
		"storico" : "History",
		"forum" : "Forum",
		"confSched" : "Scheduling",
		"confDisp" : "Appliances",
		"confUtente" : "User",
		"confImpost" : "Settings",
		"contatti" : "Contact",
		"tariffa" : "Tariff",
		"questionari" : "Forms",
		"informazioni" : "Information",
		"report" : "Report",
		"registrazione" : "Registry Maintenance",
		"opzioniLocal" : "OverLoad Warning"
	},
	config : {
		"titoloUtente" : "USER IDENTIFICATION",
		"txtUtente" : "User Identificator: ",
		"maxPotenza" : "Meter Max Power",
		"maxProduzione" : "Power Meter Production",
		"titoloDisp" : "APPLIANCES CONFIGURATION",
		"titoloStato" : "State",
		"Salva" : "Save",
		"Annulla" : "Cancel",
		"buttonAggiungi" : "Add Appliance",
		"buttonConfigura" : "Configure",
		"Chiudi" : "Close",
		"OK" : "OK",
		"Elimina" : "Delete",
		"Modifica" : "Update",
		"insPlug" : "Insert a smartplug",
		"insOk" : "Appliance inserted correctly",
		"noPlug" : "No appliance found",
		"trovatoPlug" : "Smartplug found!<br> Do you want to configure it?",
		"confermaCanc" : "Are you sure you want to delete it?",
		"txtNome" : "Name : ",
		"txtCategoria" : "Category : ",
		"txtLocazione" : "Location : ",
		"txtIcona" : "Icon :  ",
		"txtTipo" : "Type :  ",
		"txtId" : "ID :  ",
		"errorIdUtente" : "Usert Id not correct",
		"errorInsDisp" : "Error in appliance insertion",
		"errorInitRic" : "Error in init smart plug search",
		"errorAG" : "Error in gateway communication",
		"nd" : "na",
		"on" : "On",
		"off" : "Off",
		"connesso" : "Connected",
		"disconnesso" : "Not Connected",
		"autenticazioneOk" : "<b>Autentication:</b> ok",
		"autenticazioneFallita" : "<b>Autentication:</b> failed",
		"ultimoAggiornamento" : "<b>Last Server Update:</b>"
	},
	home : {
		"costiVuoto" : "This function is not available at the moment. <br> You'll be able to consult your house costs beyond your energy consumption in the second part of the trial.",
		"costi" : "Cost",
		"titoloPV" : "Photovoltaic",
		"titoloConsumi" : "Cost/Consumptions",
		"titoloCostoConsumi" : "Energy Information",
		"titoloCostiInfo" : "Cost Information",
		"titoloCosti" : "YOUR HOUSE COST",
		"costoFinora" : "Today cost",
		"costoPrevisto" : "Predicted for the month",
		"indicatoreIAC" : "WEEKLY SELF CONSUMPTION INDEX",
		"suddivisioneCosti" : "Cost Allocation",
		"indicatoreCosti" : "Your trend today",
		"indicatoreSopra" : "ABOVE THE AVERAGE",
		"indicatoreMedia" : "ON THE AVERAGE",
		"indicatoreSotto" : "BELOW THE AVERAGE",
		"costoVerde" : "<b>Very good!</b><br>You�re under your average",
		"costoGiallo" : "<b>Good</b><br>You�re on your average",
		"costoRosso" : "<b>Attention!</b><br>You�re above your average",
		"costoVuoto" : "<b>N.A.</b>",
		"spesaMensile" : "YOUR MONTHLY EXPENSES",
		"tariffa" : "Your tariff",
		"suddivisioneVuoto" : "Data not available",
		"suggerimenti" : "SUGGESTIONS",
		"consumi" : "Consumption",
		"titoloConsumi" : "Consumption",
		"titoloConsumiPV" : "Consumption",
		"titoloProduzione" : "PV Production",
		"titoloReteOut" : "Power to the grid",
		"titoloReteIn" : "Power Purchased",
		"consumoFinora" : "Energy used today",
		"consumoPrevisto" : "Predicted for the month",
		"consumoDayWeek" : "Daily average of this week",
		"costoDayWeek" : "Daily average of this week",
		"indicatoreConsumi" : "Your Trend Today",
		"consumoOdierno" : "Energy used today",
		"forecastOdierno" : "Production Forecast today",
		"labelkWh" : "kWh",
		"labelOra" : "h",
		"noMaxDisp" : "N.A.",
		"maxDisp0" : "No appliance with significant consumption",
		"datoNonDisponibile" : "N.A.",
		"consumoMaggiore" : "What is consuming more",
		"titoloDispositivi" : "APPLIANCES MONITORING",
		"titoloConsumoDisp" : "Power Use",
		"titoloLocDisp" : "Location",
		"statoDisp" : [ "OFF", "ON", "NOT CONNECTED" ],
		"nessunDisp" : "NO APPLIANCES FOUND",
		"nonDisponibile" : "Function not yet available",
		"nonDisponibileUtente" : "Function unavailable for this user (\"demo\")",
		"titoloStorico" : "DATA HISTORY",
		"periodoStorico" : "PERIOD",
		"dispStorico" : "APPLIANCE",
		"buttonStorico" : "UPDATE",
		"giornoGrafStorico" : "DAY",
		"daGrafStorico" : "FROM",
		"aGrafStorico" : "TO",
		"dispGrafStorico" : "APPLIANCES",
		"costoGrafStorico" : "Cost",
		"consumoGrafStorico" : "Energy",
		"oraLabelStorico" : "Hour",
		"giornoLabelStorico" : "Day",
		"meseLabelStorico" : "Month",
		"noGrafStorico" : "NO DATA AVAILABLE",
		"giornoStorico" : "Day",
		"settStorico" : "Week",
		"meseStorico" : "Month",
		"annoStorico" : "Year",
		"tuttiStorico" : "Total",
		"datiMancanti" : "History data missing",
		"altro" : "Other",
		"time" : "time:",
		"titleTotDisp" : "TOTAL APPLIANCES",
		"titleAltriDisp" : "OTHER CONSUMPTION",
		"titleTotCons" : "TOTAL CONSUMPTION",
		"labelCodiceUtente" : "USER CODE ",
		"serieVenduta" : "Entered in Energy Network",
		"serieAcquistata" : "Energy Purchased by Network",
		"serieForecast" : "PV Production Forecast",
		"serieConsumi" : "Consumption",
		"serieIAC" : "PV Production",
		"costoConsumoAttualeTitleBox" : "ABOUT THE CONSUMER",
		"costoProduzioneAttualeTitleBox" : "ABOUT THE PRODUCTION",
		"costoReteAttualeTitleBox" : "ABOUT THE SUPPLY",
		"lblConsO" : "Today's consumption",
		"lblProdA" : "Current production",
		"lblPotA" : "Current power",
		"oldBrowser" : "VERSION OF THE BROWSER DOES NOT FIT! Please upgrade your browser to the latest version.",
		//box consumi nella tab "dispositivi"
		"consumptionsSummary":"Consumptions summary",
		"devicesConsumption":"Devices consumption",
		"otherConsumption":"Other consumption",
		"totalConsumption":"Total consumption"
	},
	community : {
		"titoloForum" : "ENERGY@HOME FORUM",
		"forumMsg" : "This is the forum section Energy@Home. <br>"
				+ "Here you can express your opinion, make your comments, ask for information "
				+ "to the other trialists, receive suggestions and also signal "
				+ "possible critical situations or doubts about the trial. <br>"
				+ "Enter the forum, sign in and insert as many messages as you like on one or more of the topics proposed. <br>"
				+ "Good trial!",
		"forumText" : "Click here"
	},
	opzLocal : {
		"titoloForum" : "CONFIGURATION LOCAL OPTIONS",
		"forumMsg" : "Here you get access to the local configuration of the E@H!"
	},
	trial : {
		"titoloTariffa" : "TARIFF",
		"tariffaFeriale" : "Working-Day",
		"tariffaFestiva" : "Weekend",
		"tariffaBassa" : "Low tariff",
		"tariffaMedia" : "Medium tariff",
		"tariffaAlta" : "High tariff",
		"tariffaOra" : "Hour",
		"titoloInfo" : "INFORMATION",
		"titoloTestoInfo" : '<span style="font-family:verdana, arial, sans-serif"><strong>Energy@home</strong> <span style="color:rgb(174, 201, 59)"><strong>is a no-profit association</strong></span> that, for the benefit of the environment, aims at developing &amp; <span style="color:rgb(58, 153, 71)">promoting technologies and services for energy efficiency</span> in the home based upon device to device communication.</span>',
		"membriEH" : "Membri di Energy@Home:",
		"testoInfo" : "The Energy@Home trial will last about a year and you'll be able to control your electrical consumes.<br><br>"
				+ "We suggest you to pay attention to the current tariff and try to save energy and money, consuming during the lower cost tariff.<br><br>"
				+ "You can have a use suggestion every day and you can also control your consume and cost trend in the history screen",
		"titoloContatti" : "CONTACT",
		"titoloTestoContatti" : "CONTACT DETAILS",
		"telNum" : "800 678 477",
		"email" : "energyathome@telecomitalia.it",
		"titoloQuestionari" : "Forms",
		"noQuestionari" : "No forms for the moment"
	},
	report : {
		"report" : "REPORT",
		"TitoloEventiCasa" : "HOME EVENTS :",
		"TitoloElettrodomDettaglio" : "DETAILS :",
		"ConsumiFissi" : "Consumi Fissi ",
		"ConsumoFasciaEco" : "Consumo 'fascia economica' ultimo mese  ",
		"CO2" : "CO2 Prodotta fino ad oggi : ",
		"Eldo" : "Utilizzo ieri : ",
		"ProiezioneAnno" : "Mia Proiezione Anno",
		"Media" : "Media Community",
		"TitoliAccordion" : [
				[ "Media Utilizzo Community", "Ore Stand-by [min]",
						"Previsione spesa <br/>Utilizzo + Stand-By" ],
				[ "Posizione in classifica settimanale", "Media Community",
						"Previsione di spesa annua" ],
				[ "Posizione in classifica settimanale", "Media Community",
						"Previsione di spesa annua" ],
				[ "Posizione in classifica settimanale", "Media Community",
						"Mia Proiezione Anno" ] ],
		"carosello" : [ " HOME ", " OVEN ", " REFRIGERATOR ", " PC ", " LAMP ",
				" SMART TV ", " WASHING MACHINE " ],
		"informaReport" : [
				"'i consumi elettrici' fissi sono i consumi minimi di casa tua, quelli cioe' che hai anche quando tutto sembra spento (ad esempio gli stand-by di elettrodomestici e dispositivi elettronici)",
				"I 'minuti di utilizzo' di un elettrodomestico o dispositivo elettronico sono i minuti in cui hai usato il dispositivo. I minuti di stand-by si riferiscono invece ad un dispositivo acceso ma non effettivamente utilizzato",
				"I 'consumi in fascia economica' sono i consumi elettrici che hai quando l' energia costa meno (ad esempio nella fascia serale / notturna o nei weekend)",
				"La 'produzione di CO2' indica gli effetti nocivi di un eccessivo consumo energetico sulla terra ed i suoi abitanti. Approssimativamente si producono 600 g di CO2 per KWh consumato" ]
	},
	daysOfWeek : [ "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" ],
	mesiAbbrev : [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug",
			"Sep", "Oct", "Nov", "Dec" ],
	mesiCompleto : [ "January", "February", "March", "April", "May", "June",
			"July", "August", "September", "October", "November", "December" ],
	visErr : [ "Error", "Connectivity error",
	           "Connection error: server is not responding",
	           "Error: data missing",
	           "Warning! The counter ENEL is not configured in the system Energy @ Home",
			   "User identification not found.",
			   "Warning! The production counter is not configured in the system Energy @ Home"],
	locazioni : {
		"cucina" : "Kitchen",
		"bagno" : "Bathroom",
		"studio" : "Studio",
		"giardino" : "Garden",
		"bedroom" : "Camera da letto",
		"living room" : "Living Room",
		"lab" : "Lab",
		"ingresso" : "Hall",
		"corridoio" : "Corridor",
		"altro" : "Other"
	},
	storico : [ "Hour of day", "Day of week", "Day of month", "Month of year" ],
	titleGraphStorico : [ "Consumption", "Cost", "PV Production" ],
	deviceConsConsumi : [ "recharging mobile or tablet", "turning on PC or TV",
			"turning on vacuum or electric broom",
			"turning on air conditioner or dehumidifier",
			"turning on a large appliance (dishwasher, washing machine or oven)" ],
	consigliConsumi : [ "IMPORTANT ", "Your PhotoVoltaic system suggests ",
			" now", "", "" ],
	stanze : {
		0 : "Other",
		1 : "Kitchen",
		2 : "Studio",
		3 : "Garden",
		4 : "Bathroom",
		5 : "Bedroom",
		6 : "Living Room",
		7 : "Lab",
		8 : "Hall",
		9 : "Corridor"
	},
	dispositivi : {
		1 : "Other",
		2 : "Lamp",
		3 : "Water Heater",
		4 : "TV",
		5 : "PC",
		6 : "Oven",
		7 : "Iron",
		8 : "Refrigerator",
		9 : "Dish Washer",
		10 : "Air Conditioner",
		11 : "Washing Machine",
		12 : "Smart Info",
		13 : "Jolly",
		14 : "Production Meter",
		15 : "Secondary Meter",
		16 : "Printer",
		17 : "Modem/Router",
		18 : "Decoder/Recorder/Player",
		19 : "Home Theatre/Stereo",
		20 : "Play Station",
		21 : "Media Center",
		22 : "Freezer",
		23 : "Washer Dryer",
		24 : "Vacuum Cleaner",
		25 : "Hair Dryer",
		26 : "Bread Machine",
		27 : "Coffee Machine",
		28 : "Toaster",
		29 : "Food Robot",
		30 : "Water Purifier",
		31 : "Hob",
		32 : "Electric Heater",
		33 : "Swimming pool pump",
		34 : "MAC Lamp",
		35 : "Philips Lamp",
		36 : "Centralite Thermostat",
		37 : "Indesit Whashing Machine",
		38 : "Indesit Oven",
		39 : "Indesit Fridge",
		40 : "Door Lock",
		41 : "Reloc Temperature Sensor",
		42 : "Ubisys Drimmer Switch",
		43 : "Ubisys Dimmable Light",
		44 : "Window Covering",
		45 : "Window Covering Controller",
		46 : "Indesit Dish Washer"
	}
}
