var Msg = {
	NA : "ND",
	menu : {
		"home" : "Home",
		"config" : "Configurazioni",
		"community" : "Community",
		"infotrial" : "Tutto sul trial",
		"costi" : "Costi",
		"consumi" : "Consumi",
		"fv" : "FotoVoltaico",
		"dispositivi" : "Dispositivi",
		"storico" : "Storico",
		"forum" : "Forum",
		"confSched" : "Schedulazione",
		"confDisp" : "Dispositivi",
		"confUtente" : "Utente",
		"confImpost" : "Impostazioni",
		"contatti" : "Contatti",
		"tariffa" : "Tariffa",
		"questionari" : "Questionari",
		"informazioni" : "Informazioni",
		"report" : "Report",
		"registrazione" : "Gestione Registrazione",
		"opzioniLocal" : "Gestione Sovraccarico"
	},
	config : {
		"titoloUtente" : "IDENTIFICAZIONE UTENTE",
		"txtUtente" : "Identificativo Utente",
		"maxPotenza" : "Potenza Contatore Consumi",
		"maxProduzione" : "Potenza Contatore Produzione",
		"titoloDisp" : "CONFIGURAZIONE DISPOSITIVI",
		"titoloStato" : "Stato",
		"Salva" : "Salva",
		"Annulla" : "Annulla",
		"buttonAggiungi" : "Aggiungi dispositivo",
		"buttonConfigura" : "Configura",
		"Chiudi" : "Chiudi",
		"OK" : "OK",
		"Elimina" : "Elimina",
		"Modifica" : "Modifica",
		"insPlug" : "Inserisci un dispositivo",
		"insOk" : "Dispositivo inserito correttamente",
		"noPlug" : "Nessun dispositivo trovato",
		"trovatoPlug" : "Trovato un dispositivo!<br> Vuoi configurarlo?",
		"confermaCanc" : "Sei sicuro di volerlo eliminare?",
		"txtNome" : "Nome : ",
		"txtCategoria" : "Categoria : ",
		"txtLocazione" : "Locazione : ",
		"txtIcona" : "Icona :  ",
		"txtTipo" : "Tipo :  ",
		"txtId" : "ID :  ",
		"errorIdUtente" : "Id utente non corretto",
		"errorInsDisp" : "Errore in inserimento dispositivo",
		"errorInitRic" : "Problemi con l'adattatore ZigBee",
		"errorAG" : "Errore nella comunicazione con il gateway",
		"nd" : "nd",
		"on" : "Acceso",
		"off" : "Spento",
		"connesso" : "Connesso",
		"disconnesso" : "Non Connesso",
		"autenticazioneOk" : "Autenticazione: ok",
		"autenticazioneFallita" : "Autenticazione: fallita",
		"ultimoAggiornamento" : "Ultimo aggiornamento sul server: "
	},
	Configurazioni : {
		"titoloRegistrazione" : "Gestione Registrazione",
		"RegistrazioneEmail" : "Email",
		"RegistrazioneEmailConf" : "Conferma Email",
		"RegistrazionePassword" : "Password",
		"RegistrazionePasswordConf" : "Conferma Password",
		"RegistrazioneSubmitButt" : "Registra",
		"RegistrazioneCancellaButt" : "Cancella"
	},
	home : {
		"costiVuoto" : "Questa funzione non è ancora disponibile. <br> Potrai consultare i costi di casa tua oltre ai tuoi consumi nella seconda parte del trial",
		"titoloPV" : "FOTOVOLTAICO",
		"titoloConsumi" : "Consumi",
		"titoloCostoConsumi" : "Consumi",
		"titoloCostiInfo" : "Dati sui Costi",
		"titoloCosti" : "QUANTO STAI SPENDENDO",
		"costoFinora" : "Oggi finora hai speso",
		"costoPrevisto" : "Previsto per il mese",
		"indicatoreIAC" : "INDICATORE DI AUTO CONSUMO SETTIMANALE",
		"suddivisioneCosti" : "Suddivisione dei consumi",
		"indicatoreCosti" : "Andamento rispetto alla media",
		"indicatoreSopra" : "SOPRA LA MEDIA",
		"indicatoreMedia" : "IN MEDIA",
		"indicatoreSotto" : "SOTTO LA MEDIA",
		"costoVerde" : "<b>Bravo!<br>Sei sotto la tua media giornaliera</b>",
		"costoGiallo" : "<b>Bene!<br>Sei in linea con i tuoi costi giornalieri</b>",
		"costoRosso" : "<b>Attenzione!<br>Sei sopra la tua media giornaliera</b>",
		"costoVuoto" : "<b>N.D.</b>",
		"spesaMensile" : "SPESE DEGLI ULTIMI 30 GIORNI", // "LE TUE SPESE MENSILI",
		"consumoMensile" : "CONSUMO DEGLI ULTIMI 30 GIORNI", // "LE TUE SPESE MENSILI",
		"tariffa" : "La tua tariffa",
		"suddivisioneVuoto" : "Dati non disponibili",
		"suggerimenti" : "NEWS",
		"costi" : "Costi",
		"consumi" : "Consumi",
		"titoloConsumi" : "Consumo Attuale",
		"titoloConsumiPV" : "KW CONSUMATA",
		"titoloProduzione" : "Produzione Attuale",
		"titoloReteOut" : "Immissione in rete",
		"titoloReteIn" : "Acquisizione da rete",
		"consumoFinora" : "Consumi di oggi",
		"consumoPrevisto" : "Previsto per il mese",
		"consumoDayWeek" : "Media settimanale",
		"costoDayWeek" : "Media settimanale",
		"costoFinora" : "Costi di oggi",
		"costoPrevisto" : "Previsto per il mese",
		"indicatoreConsumi" : "COME STAI ANDANDO",
		"consumoOdierno" : "QUANTA ENERGIA HAI USATO OGGI",
		"forecastOdierno" : "PREVISIONE DI PRODUZIONE DI OGGI",
		"labelkWh" : "kWh",
		"labelOra" : "h",
		"noMaxDisp" : "N.D.",
		"maxDisp0" : "Nessun elettrodomestico ha un consumo significativo",
		"datoNonDisponibile" : "N.D.",
		"consumoMaggiore" : "CONSUMO MAGGIORE",
		"titoloDispositivi" : "CONTROLLO DISPOSITIVI",
		"titoloConsumoDisp" : "Sta consumando",
		"titoloLocDisp" : "Dove si trova",
		"statoDisp" : [ "SPENTO", "ACCESO", "NON CONNESSO", "STAND-BY" ],
		"nessunDisp" : "NESSUN DISPOSITIVO TROVATO",
		"nonDisponibile" : "Funzione non ancora disponibile",
		"nonDisponibileUtente" : "Funzione non disponibile per questo utente (\"demo\")",
		"titoloStorico" : "STORICO DEI DATI",
		"periodoStorico" : "PERIODO",
		"dispStorico" : "DISPOSITIVO",
		"buttonStorico" : "AGGIORNA",
		"giornoGrafStorico" : "GIORNO",
		"daGrafStorico" : "DAL",
		"aGrafStorico" : "AL",
		"dispGrafStorico" : "DISPOSITIVO",
		"costoGrafStorico" : "Costo",
		"consumoGrafStorico" : "Consumo",
		"oraLabelStorico" : "Ora",
		"giornoLabelStorico" : "Giorno",
		"meseLabelStorico" : "Mese",
		"noGrafStorico" : "NESSUN DATO DISPONIBILE",
		"giornoStorico" : "Giorno",
		"settStorico" : "Settimana",
		"meseStorico" : "Mese",
		"annoStorico" : "Anno",
		"tuttiStorico" : "Totale",
		"datiMancanti" : "Dati storici non completi",
		"altro" : "Altro",
		"time" : "alle ore:",
		"titleTotDisp" : "TOTALE DISPOSITIVI MONITORATI",
		"titleAltriDisp" : "ALTRI CONSUMI",
		"titleTotCons" : "CONSUMI TOTALI",
		"labelCodiceUtente" : "CODICE UTENTE ",
		"serieVenduta" : "Energia Immessa in Rete",
		"serieAcquistata" : "Energia Acquistata dalla Rete",
		"serieForecast" : "Energia Prodotta prevista",
		"serieConsumi" : "Consumi",
		"serieIAC" : "Produzione",
		"costoConsumoAttualeTitleBox" : "INFORMAZIONI SUL TUO CONSUMO DI OGGI DA MEZZANOTTE A QUESTO MOMENTO",
		"costoProduzioneAttualeTitleBox" : "INFORMAZIONI RELATIVE ALLA PRODUZIONE ATTUALE",
		"costoReteAttualeTitleBox" : "INFORMAZIONI RELATIVE ALLA FORNITURA ATTUALE",
		"lblConsO" : "Consumo Odierno",
		"lblProdA" : "Produzione Attuale",
		"lblPotA" : "Potenza Attuale",
		"oldBrowser" : "VERSIONE DEL BROWSER NON ADATTA! Si prega di aggiornare il browser con l'ultima versione.",
		//box consumi nella tab "dispositivi"
		"consumptionsSummary":"Riepilogo consumi",
		"devicesConsumption":"Consumo dispositivi",
		"otherConsumption":"Altri consumi",
		"totalConsumption":"Consumo totale"
	},
	community : {
		"titoloForum" : "FORUM ENERGY@HOME",
		"forumMsg" : "Questa e' la sezione del forum Energy@Home. <br>Qui potrai esprimere la tua opinione, fare i tuoi commenti, chiedere informazioni agli altri partecipanti del trial, ricevere suggerimenti ed anche segnalare eventuali criticita' o dubbi sulla sperimentazione. <br>Accedi al forum, registrati e poi inserisci tanti messaggi quanti vuoi su uno o pi� dei 'topic' proposti. <br>Buona sperimentazione!",
		"forumText" : "Clicca qui"
	},
	opzLocal : {
		"titoloForum" : "OPZIONI DI CONFIGURAZIONE LOCALE",
		"forumMsg" : "Qui accedi alla configurazione locale del sistema E@H!"
	},
	trial : {
		"titoloTariffa" : "TARIFFA",
		"tariffaFeriale" : "Feriale",
		"tariffaFestiva" : "Festiva",
		"tariffaBassa" : "Tariffa Bassa",
		"tariffaMedia" : "Tariffa Media",
		"tariffaAlta" : "Tariffa Alta",
		"tariffaOra" : "Ora",
		"titoloInfo" : "INFORMAZIONI",
		"titoloTestoInfo" : "Clicca qui per maggiori informazioni sul trial",
		"membriEH" : "Membri di Energy@Home:" ,
		"testoInfo" : "Il trial Energy@Home avra' la durata di un anno circa e ti consentira' di controllare i tuoi consumi elettrici.<br><br>Ti suggeriamo di guardare con attenzione le tariffe in uso e di provare a risparmiare, consumando nelle fasce a minor costo.<br><br>Potrai anche confrontare i tuoi consumi con quelli degli altri partecipanti al trial e darci i tuoi suggerimenti andando nella community.",
		"titoloContatti" : "CONTATTI",
		"titoloTestoContatti" : "SE VUOI CONTATTARCI",
		"telNum" : "800 678 477",
		"email" : "energyathome@telecomitalia.it",
		"titoloQuestionari" : "QUESTIONARI",
		"noQuestionari" : "Attualmente non sono presenti questionari"
	},
	report : {
		"report" : "REPORT",
		"TitoloEventiCasa" : "I TUOI CONSUMI :",
		"TitoloElettrodomDettaglio" : "DETTAGLI :",
		"ConsumiFissi" : "Consumi Fissi ",
		"ConsumoFasciaEco" : "Consumo 'fascia economica' ultimo mese  ",
		"CO2" : "CO2 Prodotta fino ad oggi : ",
		"Eldo" : "Utilizzo ieri : ",
		"ProiezioneAnno" : "Mia Proiezione Anno",
		"Media" : "Media Community",
		"TitoliAccordion" : [[ "Media Utilizzo Community", "Ore Stand-by [min]", "Previsione spesa <br/>Utilizzo + Stand-By" ],
						     [ "Posizione in classifica settimanale", "Media Community", "Previsione di spesa annua" ],
						     [ "Posizione in classifica settimanale", "Media Community", "Previsione di spesa annua" ],
						     [ "Posizione in classifica settimanale", "Media Community", "Mia Proiezione Anno" ]],
		"carosello" : [ " CASA ", " FORNO ", " FRIGO ", " PC ", " LAMPADA ", " SMART TV ", " LAVATRICE " ],
		"informaReport" : [
				"I 'consumi elettrici' fissi sono i consumi minimi di casa tua, quelli cioe' che hai anche quando tutto sembra spento (ad esempio gli stand-by di elettrodomestici e dispositivi elettronici)",
				"I 'minuti di utilizzo' di un elettrodomestico o dispositivo elettronico sono i minuti in cui hai usato il dispositivo. I minuti di stand-by si riferiscono invece ad un dispositivo acceso ma non effettivamente utilizzato",
				"I 'consumi in fascia economica' sono i consumi elettrici che hai quando l' energia costa meno (ad esempio nella fascia serale / notturna o nei weekend)",
				"La 'produzione di CO2' indica gli effetti nocivi di un eccessivo consumo energetico sulla terra ed i suoi abitanti. Approssimativamente si producono 600 g di CO2 per KWh consumato" ]
	},
	daysOfWeek : [ "Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom" ],
	mesiAbbrev : [ "Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic" ],
	mesiCompleto : [ "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre" ],
	visErr : [
			"Errore",
			"Errore di connettivita'",
			"Errore di connessione: il server non risponde",
			"Errore: dati mancanti",
			"Attenzione! Il contatore ENEL non e' configurato nel sistema Energy@Home",
			"Identificativo Utente non trovato.",
			"Impianto PV non configurato"],
			//"Attenzione! Il contatore di produzione non e' configurato nel sistema Energy@Home"],
	locazioni : {
		"kitchen" : "Cucina",
		"bathroom" : "Bagno",
		"studio" : "Studio",
		"garden" : "Giardino",
		"bedroom" : "Camera da letto",
		"living room" : "Soggiorno",
		"lab" : "Laboratorio",
		"hall" : "Ingresso",
		"corridor" : "Corridoio",
		"other" : "Altro"
	},
	storico : [ "Ora del giorno", "Giorno della settimana", "Giorno del mese", "Mese dell'anno" ],
	titleGraphStorico : [ "Consumi", "Costi", "Produzione" ],
	deviceConsConsumi : [ "ricaricare cellulare o tablet", "accendere PC o TV",
	                      "accendere aspirapolvere o scopa elettrica",
	                      "accendere condizionatore o deumidificatore",
	                      "accendere un grande elettrodomestico (lavastoviglie, lavatrice o forno)" ],
	consigliConsumi : [ "IMPORTANTE ", "Il tuo impianto fotovoltaico ti suggerisce di ", " ora", "", "" ],
	stanze : {
		0 : "Altro",
		1 : "Cucina",
		2 : "Studio",
		3 : "Giardino",
		4 : "Bagno",
		5 : "Camera da letto",
		6 : "Soggiorno",
		7 : "Laboratorio",
		8 : "Ingresso",
		9 : "Corridoio",
		10 : "Presa SmartInfo"
	},
	dispositivi : {
		1 : "Altro",
		2 : "Lampada",
		3 : "Boiler",
		4 : "TV",
		5 : "PC",
		6 : "Forno",
		7 : "Ferro da stiro",
		8 : "Frigorifero",
		9 : "Lavastoviglie",
		10 : "Condizionatore",
		11 : "Lavatrice",
		12 : "Smart Info",
		13 : "Jolly SmartPlug",
		14 : "Contatore fotovoltaico",
		15 : "Contatore secondario",
		16 : "Stampante",
		17 : "Modem/Router",
		18 : "Decoder/Recorder/Player",
		19 : "Home Theatre/Stereo",
		20 : "Play Station",
		21 : "Media Center",
		22 : "Congelatore",
		23 : "Asciugatrice",
		24 : "Aspirapolvere",
		25 : "Phon",
		26 : "Macchina del pane",
		27 : "Macchina del caff�",
		28 : "Tosta pane",
		29 : "Robot cucina",
		30 : "Depuratore acqua",
		31 : "Piano cottura",
		32 : "Stufa elettrica",
		33 : "Pompa piscina",
		34 : "Lampada Mac",
		35 : "Lampada Philips",
		36 : "Termostato Centralite",
		37 : "Lavatrice Indesit",
		38 : "Forno Indesit",
		39 : "Frigorifero Indesit",
		40 : "Serratura porta",
		41 : "Sensore di Temperatura Reloc",
		42 : "Regolatore intensità Ubisys",
		43 : "Attenuatore di luce Ubisys",
		44 : "Tapparella finestra",
		45 : "Controllore Tapparella finestra",
		46 : "Lavastoviglie Indesit"
		
			
	}
}
