/**
 * This file is part of JEMMA - http://jemma.energy-home.org
 * (C) Copyright 2013 Telecom Italia (http://www.telecomitalia.it)
 *
 * JEMMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) version 3
 * or later as published by the Free Software Foundation, which accompanies
 * this distribution and is available at http://www.gnu.org/licenses/lgpl.html
 *
 * JEMMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License (LGPL) for more details.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.05 at 12:25:32 PM CEST 
//


package org.energy_home.jemma.m2m.ah;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.energy_home.jemma.m2m.ah package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.energy_home.jemma.m2m.ah
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FloatCDV }
     * 
     */
    public FloatCDV createFloatCDV() {
        return new FloatCDV();
    }

    /**
     * Create an instance of {@link DoubleCDV }
     * 
     */
    public DoubleCDV createDoubleCDV() {
        return new DoubleCDV();
    }

    /**
     * Create an instance of {@link FloatDV }
     * 
     */
    public FloatDV createFloatDV() {
        return new FloatDV();
    }

    /**
     * Create an instance of {@link DoubleDV }
     * 
     */
    public DoubleDV createDoubleDV() {
        return new DoubleDV();
    }
    
	/**
	 * Create an instance of {@link EnergyCostPowerInfo }
	 * 
	 */
	public EnergyCostPowerInfo createEnergyCostPowerInfo() {
		return new EnergyCostPowerInfo();
	}
	
	/**
	 * Create an instance of {@link ApplianceLog }
	 * 
	 */
	public ApplianceLog createApplianceLog() {
		return new ApplianceLog();
	}

}
