/**
 * This file is part of JEMMA - http://jemma.energy-home.org
 * (C) Copyright 2013 Telecom Italia (http://www.telecomitalia.it)
 *
 * JEMMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) version 3
 * or later as published by the Free Software Foundation, which accompanies
 * this distribution and is available at http://www.gnu.org/licenses/lgpl.html
 *
 * JEMMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License (LGPL) for more details.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.03 at 05:23:14 PM CEST 
//


package org.energy_home.jemma.zgd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Action complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Action">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecodeSpecification">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DecodeLevel" type="{http://www.zigbee.org/GWGSchema}DecodeLevel" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ForwardingSpecification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Action", propOrder = {
    "decodeSpecification",
    "forwardingSpecification"
})
public class Action {

    @XmlElement(name = "DecodeSpecification", required = true)
    protected Action.DecodeSpecification decodeSpecification;
    @XmlElement(name = "ForwardingSpecification", required = true)
    protected String forwardingSpecification;

    /**
     * Gets the value of the decodeSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link Action.DecodeSpecification }
     *     
     */
    public Action.DecodeSpecification getDecodeSpecification() {
        return decodeSpecification;
    }

    /**
     * Sets the value of the decodeSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action.DecodeSpecification }
     *     
     */
    public void setDecodeSpecification(Action.DecodeSpecification value) {
        this.decodeSpecification = value;
    }

    /**
     * Gets the value of the forwardingSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingSpecification() {
        return forwardingSpecification;
    }

    /**
     * Sets the value of the forwardingSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingSpecification(String value) {
        this.forwardingSpecification = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DecodeLevel" type="{http://www.zigbee.org/GWGSchema}DecodeLevel" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "decodeLevel"
    })
    public static class DecodeSpecification {

        @XmlElement(name = "DecodeLevel", required = true)
        protected List<DecodeLevel> decodeLevel;

        /**
         * Gets the value of the decodeLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the decodeLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDecodeLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DecodeLevel }
         * 
         * 
         */
        public List<DecodeLevel> getDecodeLevel() {
            if (decodeLevel == null) {
                decodeLevel = new ArrayList<DecodeLevel>();
            }
            return this.decodeLevel;
        }

    }

}
