//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:45:34 PM CET 
//


package org.energy_home.jemma.zgd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescriptorCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptorCapability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExtendedActiveEndpointListAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ExtendedSimpleDescriptorListAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptorCapability", propOrder = {
    "extendedActiveEndpointListAvailable",
    "extendedSimpleDescriptorListAvailable"
})
public class DescriptorCapability {

    @XmlElement(name = "ExtendedActiveEndpointListAvailable")
    protected boolean extendedActiveEndpointListAvailable;
    @XmlElement(name = "ExtendedSimpleDescriptorListAvailable")
    protected boolean extendedSimpleDescriptorListAvailable;

    /**
     * Gets the value of the extendedActiveEndpointListAvailable property.
     * 
     */
    public boolean isExtendedActiveEndpointListAvailable() {
        return extendedActiveEndpointListAvailable;
    }

    /**
     * Sets the value of the extendedActiveEndpointListAvailable property.
     * 
     */
    public void setExtendedActiveEndpointListAvailable(boolean value) {
        this.extendedActiveEndpointListAvailable = value;
    }

    /**
     * Gets the value of the extendedSimpleDescriptorListAvailable property.
     * 
     */
    public boolean isExtendedSimpleDescriptorListAvailable() {
        return extendedSimpleDescriptorListAvailable;
    }

    /**
     * Sets the value of the extendedSimpleDescriptorListAvailable property.
     * 
     */
    public void setExtendedSimpleDescriptorListAvailable(boolean value) {
        this.extendedSimpleDescriptorListAvailable = value;
    }

}
