//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:45:34 PM CET 
//


package org.energy_home.jemma.zgd.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Neighbor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Neighbor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShortAddress" type="{http://www.zigbee.org/GWGSchema}NetworkAddress"/>
 *         &lt;element name="IeeeAddress" type="{http://www.zigbee.org/GWGSchema}IeeeAddress"/>
 *         &lt;element name="DeviceTypeRxOnWhenIdleRelationship" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="Depth" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="LQI" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Neighbor", propOrder = {
    "shortAddress",
    "ieeeAddress",
    "deviceTypeRxOnWhenIdleRelationship",
    "depth",
    "lqi"
})
public class Neighbor {

    @XmlElement(name = "ShortAddress")
    protected int shortAddress;
    @XmlElement(name = "IeeeAddress", required = true)
    protected BigInteger ieeeAddress;
    @XmlElement(name = "DeviceTypeRxOnWhenIdleRelationship")
    @XmlSchemaType(name = "unsignedByte")
    protected short deviceTypeRxOnWhenIdleRelationship;
    @XmlElement(name = "Depth")
    @XmlSchemaType(name = "unsignedByte")
    protected short depth;
    @XmlElement(name = "LQI")
    @XmlSchemaType(name = "unsignedByte")
    protected short lqi;

    /**
     * Gets the value of the shortAddress property.
     * 
     */
    public int getShortAddress() {
        return shortAddress;
    }

    /**
     * Sets the value of the shortAddress property.
     * 
     */
    public void setShortAddress(int value) {
        this.shortAddress = value;
    }

    /**
     * Gets the value of the ieeeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIeeeAddress() {
        return ieeeAddress;
    }

    /**
     * Sets the value of the ieeeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIeeeAddress(BigInteger value) {
        this.ieeeAddress = value;
    }

    /**
     * Gets the value of the deviceTypeRxOnWhenIdleRelationship property.
     * 
     */
    public short getDeviceTypeRxOnWhenIdleRelationship() {
        return deviceTypeRxOnWhenIdleRelationship;
    }

    /**
     * Sets the value of the deviceTypeRxOnWhenIdleRelationship property.
     * 
     */
    public void setDeviceTypeRxOnWhenIdleRelationship(short value) {
        this.deviceTypeRxOnWhenIdleRelationship = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     */
    public short getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     */
    public void setDepth(short value) {
        this.depth = value;
    }

    /**
     * Gets the value of the lqi property.
     * 
     */
    public short getLQI() {
        return lqi;
    }

    /**
     * Sets the value of the lqi property.
     * 
     */
    public void setLQI(short value) {
        this.lqi = value;
    }

}
