//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:45:34 PM CET 
//


package org.energy_home.jemma.zgd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkDescriptorList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkDescriptorList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetworkDescriptor" type="{http://www.zigbee.org/GWGSchema}NetworkDescriptor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkDescriptorList", propOrder = {
    "networkDescriptor"
})
public class NetworkDescriptorList {

    @XmlElement(name = "NetworkDescriptor", required = true)
    protected NetworkDescriptor networkDescriptor;

    /**
     * Gets the value of the networkDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkDescriptor }
     *     
     */
    public NetworkDescriptor getNetworkDescriptor() {
        return networkDescriptor;
    }

    /**
     * Sets the value of the networkDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkDescriptor }
     *     
     */
    public void setNetworkDescriptor(NetworkDescriptor value) {
        this.networkDescriptor = value;
    }

}
