//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:45:34 PM CET 
//


package org.energy_home.jemma.zgd.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unsecured"/>
 *     &lt;enumeration value="SecuredNwkKey"/>
 *     &lt;enumeration value="SecuredLinkKey"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecurityStatus")
@XmlEnum
public enum SecurityStatus {

    @XmlEnumValue("Unsecured")
    UNSECURED("Unsecured"),
    @XmlEnumValue("SecuredNwkKey")
    SECURED_NWK_KEY("SecuredNwkKey"),
    @XmlEnumValue("SecuredLinkKey")
    SECURED_LINK_KEY("SecuredLinkKey");
    private final String value;

    SecurityStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SecurityStatus fromValue(String v) {
        for (SecurityStatus c: SecurityStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
