//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:45:34 PM CET 
//


package org.energy_home.jemma.zgd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZCLCommandResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZCLCommandResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceEndpoint" type="{http://www.zigbee.org/GWGSchema}Endpoint"/>
 *         &lt;element name="CommandID" type="{http://www.zigbee.org/GWGSchema}CommandIdentifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZCLCommandResult", propOrder = {
    "sourceEndpoint",
    "commandID"
})
public class ZCLCommandResult {

    @XmlElement(name = "SourceEndpoint")
    protected short sourceEndpoint;
    @XmlElement(name = "CommandID")
    protected int commandID;

    /**
     * Gets the value of the sourceEndpoint property.
     * 
     */
    public short getSourceEndpoint() {
        return sourceEndpoint;
    }

    /**
     * Sets the value of the sourceEndpoint property.
     * 
     */
    public void setSourceEndpoint(short value) {
        this.sourceEndpoint = value;
    }

    /**
     * Gets the value of the commandID property.
     * 
     */
    public int getCommandID() {
        return commandID;
    }

    /**
     * Sets the value of the commandID property.
     * 
     */
    public void setCommandID(int value) {
        this.commandID = value;
    }

}
