/**
 * This file is part of JEMMA - http://jemma.energy-home.org
 * (C) Copyright 2013 Telecom Italia (http://www.telecomitalia.it)
 *
 * JEMMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) version 3
 * or later as published by the Free Software Foundation, which accompanies
 * this distribution and is available at http://www.gnu.org/licenses/lgpl.html
 *
 * JEMMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License (LGPL) for more details.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.03 at 05:23:14 PM CEST 
//


package org.energy_home.jemma.zgd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ZDPCommand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZDPCommand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Destination" type="{http://www.zigbee.org/GWGSchema}Address"/>
 *         &lt;element name="TxOptions" type="{http://www.zigbee.org/GWGSchema}TxOptions" minOccurs="0"/>
 *         &lt;element name="Radius" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="ClusterID" type="{http://www.zigbee.org/GWGSchema}ClusterIdentifier"/>
 *         &lt;element name="Command" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *         &lt;element name="DestinationAddrMode" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZDPCommand", propOrder = {
    "destination",
    "txOptions",
    "radius",
    "clusterID",
    "command",
    "destinationAddrMode"
})
public class ZDPCommand {

    @XmlElement(name = "Destination", required = true)
    protected Address destination;
    @XmlElement(name = "TxOptions")
    protected TxOptions txOptions;
    @XmlElement(name = "Radius")
    @XmlSchemaType(name = "unsignedByte")
    protected Short radius;
    @XmlElement(name = "ClusterID")
    protected int clusterID;
    @XmlElement(name = "Command", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] command;
    @XmlElement(name = "DestinationAddrMode")
    @XmlSchemaType(name = "unsignedInt")
    protected long destinationAddrMode;

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setDestination(Address value) {
        this.destination = value;
    }

    /**
     * Gets the value of the txOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TxOptions }
     *     
     */
    public TxOptions getTxOptions() {
        return txOptions;
    }

    /**
     * Sets the value of the txOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxOptions }
     *     
     */
    public void setTxOptions(TxOptions value) {
        this.txOptions = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRadius(Short value) {
        this.radius = value;
    }

    /**
     * Gets the value of the clusterID property.
     * 
     */
    public int getClusterID() {
        return clusterID;
    }

    /**
     * Sets the value of the clusterID property.
     * 
     */
    public void setClusterID(int value) {
        this.clusterID = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(byte[] value) {
        this.command = ((byte[]) value);
    }

    /**
     * Gets the value of the destinationAddrMode property.
     * 
     */
    public long getDestinationAddrMode() {
        return destinationAddrMode;
    }

    /**
     * Sets the value of the destinationAddrMode property.
     * 
     */
    public void setDestinationAddrMode(long value) {
        this.destinationAddrMode = value;
    }

}
