/**
 * 
 */

var LANG = {
	NA : "ND",
	menu : {btnChannelNetwork : "Manage network channel",
		    btnVersionJGal : "Versione JavaGal",
		    btnViewDevice : "Visualizzazione device",
		    btnViewGraphNodes : "Visualizzazione grafo dei nodi",
		    btnInsertDevice : "Inserimento nuovi device",
		    btnManageNetwork : "Gestione Rete ZigBee"
	},
	centerPane: {btnAutomaticScan : "Automatic",
	             btnManualScan : "Change",
	             lblVersionId: "Version Identifier",
	             lblVersionFId: "feature Set Identifier",
	             lblVersionRpcP: "rpc Protocol",
	             lblDeviceNetAdd: "network Address",
	             lblDeviceIeeAdd: "ieee Address",
	             lblDeviceSIndex: "start Index",
	             lblDeviceAssDev: "associated Devices",
	             lblDeviceAltPan: "alternate Pan Coordinator",
	             lblDeviceDevFFD: "device Is FFD",
	             lblDeviceMainPo: "mains Powered",
	             lblDeviceRecOWI: "receiver On When Idle",
	             lblDeviceSecSup: "security Supported",
	             lblDeviceAllAdd: "allocate Address",
	             lblDeviceAddress: "address",
	             lblDeviceCInfo: "capability Information",
		             lblActions: "Actions"
	            	 
	},
	networkManage: {
		btnStartGal : "Start",
	    btnRestartGal1 : "Total reset",
	    btnRestartGal2 : "Stop",
	    btnRestartGal3 : "Reset GAL TCR",
	    lblChannelMask : "Channel",
	    lblConcentratorDiscoveryTime : "Concentrator Discovery Time",
	    lblConcentratorFlag : "Concentrator Flag",
	    lblConcentratorRadius : "Concentrator Radius",
	    lblDeviceType : "Device Type",
	    lblExtendedPANId : "Extended PAN Id",
	    lblIndirectPollRate : "Indirect Poll Rate",
	    lblmaxRejoinInterval : "Max Rejoin Interval",
	    lblNetworkKey : "Network Key",
	    lblNetworkKeySeqNum : "Network Key Sequence Number",
	    lblNetworkKeyType : "Network Key Type",
	    lblNetworkManagerAddress : "Network Manager Address",
	    lblPanId : "Pan Id",
	    lblParentRetryThreshold : "Parent Retry Threshold",
	    lblPreconfiguredLinkKey : "Preconfigured Link Key",
	    lblProtocolVersion : "Protocol Version",
	    lblRejoinInterval : "Rejoin Interval",
	    lblScanAttempts : "Scan Attempts",
	    lblShortAddress : "Short Address",
	    lblStackProfile : "Stack Profile",
	    lblStartupAttributeSetIndex : "Startup Attribute Set Index",
	    lblStartupControl : "Startup Control",
	    lblTimeBetweenScans : "Time Between Scans",
	    lblTrustCenterAddress : "Trust Center Address",
	    lblTrustCenterMasterKey : "Trust Center Master Key",
	    lblUseInsecureJoin : "Use Insecure Join", 
	    lblProfileConfEndPoint: "Profile",
	    lblDeviceConfEndPoint: "Device",
	    lblEndPointEndPoint: "End Point",
	    lblProfileEndPoint: "Profile Id",
	    lblDeviceEndPoint: "Device Id",
	    lblDeviceVersEndPoint: "Device Version",
	    lblInputCluster: "Input Cluster",
	    lblOutputCluster: "Output Cluster"
	}
};