var LANG = {
	NA : "ND",
	menu : {
		btnChannelNetwork : "Advanced Controls",
		btnVersionJGal : "Java Gal Version",
		btnViewDevice : "Network devices",
		btnViewDeviceNew : "Network devices added now",
		
		btnViewGraphNodes : "Network Topology",
		btnManageNetwork : "ZigBee Network info"
	},
	centerPane : {
		btnAutomaticScan : "Automatic",
		btnManualScan : "Change",
		lblVersionId : "Version Identifier",
		lblVersionFId : "Feature Set Identifier",
		lblVersionRpcP : "Rpc Protocol",
		lblDeviceNetAdd : "Network Address",
		lblDeviceIeeAdd : "Ieee Address",
		lblDeviceSIndex : "start Index",
		lblDeviceAssDev : "Associated Devices",
		lblDeviceAltPan : "Alternate Pan Coordinator",
		lblDeviceDevFFD : "Device Is FFD",
		lblDeviceMainPo : "Mains Powered",
		lblDeviceLogical : "Device Type",
		lblDeviceRecOWI : "Receiver On When Idle",
		lblDeviceSecSup : "Security Supported",
		lblDeviceAllAdd : "Allocate Address",
		lblDeviceDiscovered : "Discovered Now",
		lblDeviceAddress : "Address",
		lblDeviceCInfo : "Capability Information",
		lblActions : "Actions",
		lblName : "Name",
		lblValue : "Value",

	},
	networkManage : {
		btnStartGal : "Start",
		btnRestartGal1 : "Total reset",
		btnRestartGal2 : "Stop",
		btnRestartGal3 : "Reset GAL TCR",
		lblChannelMask : "Channel",
		lblConcentratorDiscoveryTime : "Concentrator Discovery Time",
		lblConcentratorFlag : "Concentrator Flag",
		lblConcentratorRadius : "Concentrator Radius",
		lblDeviceType : "Device Type",
		lblExtendedPANId : "Extended PAN Id",
		lblIndirectPollRate : "Indirect Poll Rate",
		lblmaxRejoinInterval : "Max Rejoin Interval",
		lblNetworkKey : "Network Key",
		lblNetworkKeySeqNum : "Network Key Sequence Number",
		lblNetworkKeyType : "Network Key Type",
		lblNetworkManagerAddress : "Network Manager Address",
		lblPanId : "Pan Id",
		lblParentRetryThreshold : "Parent Retry Threshold",
		lblPreconfiguredLinkKey : "Preconfigured Link Key",
		lblProtocolVersion : "Protocol Version",
		lblRejoinInterval : "Rejoin Interval",
		lblScanAttempts : "Scan Attempts",
		lblShortAddress : "Short Address",
		lblStackProfile : "Stack Profile",
		lblStartupAttributeSetIndex : "Startup Attribute Set Index",
		lblStartupControl : "Startup Control",
		lblTimeBetweenScans : "Time Between Scans",
		lblTrustCenterAddress : "Trust Center Address",
		lblTrustCenterMasterKey : "Trust Center Master Key",
		lblUseInsecureJoin : "Use Insecure Join",
		lblProfileConfEndPoint : "Profile",
		lblDeviceConfEndPoint : "Device",
		lblEndPointEndPoint : "End Point",
		lblProfileEndPoint : "Profile Id",
		lblDeviceEndPoint : "Device Id",
		lblDeviceVersEndPoint : "Device Version",
		lblInputCluster : "Input Cluster",
		lblOutputCluster : "Output Cluster",
		btnAutomaticScanChannel: "Automatic channel"
	},
	
	propertyName: {
		shortAddress:"Gal short address",
		shortPanId:"Network short panID",
		extendedPanId:"Network extended panID",
		deviceType:"GAL device type",
		securityLevel:"Network security level",
		stackSoftwareVersion:"Stack version",
		networkKey:"Sas network key",
		netKey:"Network key"
		
		
		
	}
};