var Msg = {
	NA : "ND",
	menu : {
		"home" : "Home",
		"config" : "Configurazioni",
		"community" : "Community",
		"infotrial" : "Tutto sul trial",
		"costi" : "Costi",
		"consumi" : "Consumi",
		"fv" : "FotoVoltaico",
		"dispositivi" : "Dispositivi",
		"storico" : "Storico",
		"forum" : "Forum",
		"confSched" : "Schedulazione",
		"confDisp" : "Dispositivi",
		"confUtente" : "Utente",
		"confImpost" : "Impostazioni",
		"contatti" : "Contatti",
		"tariffa" : "Tariffa",
		"questionari" : "Questionari",
		"informazioni" : "Informazioni",
		"report" : "Report",
		"registrazione" : "Gestione Registrazione",
		"opzioniLocal" : "Gestione Sovraccarico"
	},
	config : {
		"titoloUtente" : "IDENTIFICAZIONE UTENTE",
		"txtUtente" : "Identificativo Utente",
		"maxPotenza" : "Potenza Contatore Consumi",
		"maxProduzione" : "Potenza Contatore Produzione",
		"titoloDisp" : "CONFIGURAZIONE DISPOSITIVI",
		"titoloStato" : "Stato",
		"Salva" : "Salva",
		"Annulla" : "Annulla",
		"buttonAggiungi" : "Aggiungi dispositivo",
		"buttonConfigura" : "Configura",
		"Chiudi" : "Chiudi",
		"OK" : "OK",
		"Elimina" : "Elimina",
		"Modifica" : "Modifica",
		"insPlug" : "Inserisci un dispositivo",
		"insOk" : "Dispositivo inserito correttamente",
		"noPlug" : "Nessun dispositivo trovato",
		"trovatoPlug" : "Trovato un dispositivo!<br> Vuoi configurarlo?",
		"confermaCanc" : "Sei sicuro di volerlo eliminare?",
		"txtNome" : "Nome : ",
		"txtCategoria" : "Categoria : ",
		"txtLocazione" : "Locazione : ",
		"txtIcona" : "Icona :  ",
		"txtTipo" : "Tipo :  ",
		"txtId" : "ID :  ",
		"errorIdUtente" : "Id utente non corretto",
		"errorInsDisp" : "Errore in inserimento dispositivo",
		"errorInitRic" : "Problemi con l'adattatore ZigBee",
		"errorAG" : "Errore nella comunicazione con il gateway",
		"nd" : "nd",
		"on" : "Acceso",
		"off" : "Spento",
		"connesso" : "Connesso",
		"disconnesso" : "Non Connesso",
		"autenticazioneOk" : "Autenticazione: ok",
		"autenticazioneFallita" : "Autenticazione: fallita",
		"ultimoAggiornamento" : "Ultimo aggiornamento sul server: "
	},
	Configurazioni : {
		"titoloRegistrazione" : "Gestione Registrazione",
		"RegistrazioneEmail" : "Email",
		"RegistrazioneEmailConf" : "Conferma Email",
		"RegistrazionePassword" : "Password",
		"RegistrazionePasswordConf" : "Conferma Password",
		"RegistrazioneSubmitButt" : "Registra",
		"RegistrazioneCancellaButt" : "Cancella"
	},
	home : {
		"costiVuoto" : "Questa funzione non � ancora disponibile. <br> Potrai consultare i costi di casa tua oltre ai tuoi consumi nella seconda parte del trial",
		"costi" : "COSTI",
		"titoloPV" : "FOTOVOLTAICO",
		"titoloConsumi" : "CONSUMI",
		"titoloCosti" : "QUANTO STAI SPENDENDO",
		"costoFinora" : "Oggi finora hai speso",
		"costoPrevisto" : "Previsto per il mese",
		"indicatoreIAC" : "INDICATORE DI AUTO CONSUMO SETTIMANALE",
		"indicatoreCosti" : "COME STAI ANDANDO",
		"indicatoreSopra" : "SOPRA LA MEDIA",
		"indicatoreMedia" : "IN MEDIA",
		"indicatoreSotto" : "SOTTO LA MEDIA",
		"costoVerde" : "<b>Bravo!<br>Sei sotto la tua media giornaliera</b>",
		"costoGiallo" : "<b>Bene!<br>Sei in linea con i tuoi costi giornalieri</b>",
		"costoRosso" : "<b>Attenzione!<br>Sei sopra la tua media giornaliera</b>",
		"costoVuoto" : "<b>Non disponibile</b>",
		"spesaMensile" : "SPESE DEGLI ULTIMI 30 GIORNI", // "LE TUE SPESE MENSILI",
		"consumoMensile" : "CONSUMO DEGLI ULTIMI 30 GIORNI", // "LE TUE SPESE MENSILI",
		"tariffa" : "La tua tariffa",
		"suddivisioneVuoto" : "Dati non disponibili",
		"suggerimenti" : "NEWS",
		"consumi" : "CONSUMI",
		"titoloConsumi" : "QUANTO STAI CONSUMANDO",
		"titoloConsumiPV" : "KW CONSUMATA",
		"titoloProduzione" : "KW PRODOTTA DA TE",
		"titoloReteOut" : "KW IMMESSA IN RETE",
		"titoloReteIn" : "KW ACQUISTATA",
		"consumoFinora" : "Oggi finora hai consumato",
		"consumoPrevisto" : "Previsto per il mese",
		"indicatoreConsumi" : "COME STAI ANDANDO",
		"consumoOdierno" : "QUANTA ENERGIA HAI USATO OGGI",
		"produzoneOdierno" : "QUANTA ENERGIA HAI COMPRATO-VENDUTO OGGI",
		"labelkWh" : "kWh",
		"labelOra" : "h",
		"noMaxDisp" : "Non disponibile",
		"maxDisp0" : "Nessun elettrodomestico ha un consumo significativo",
		"datoNonDisponibile" : "Non disponibile",
		"consumoMaggiore" : "COSA STA CONSUMANDO DI PIU'",
		"titoloDispositivi" : "CONTROLLO DISPOSITIVI",
		"titoloConsumoDisp" : "Sta consumando",
		"titoloLocDisp" : "Dove si trova",
		"statoDisp" : [ "SPENTO", "ACCESO", "NON CONNESSO", "STAND-BY" ],
		"nessunDisp" : "NESSUN DISPOSITIVO TROVATO",
		"nonDisponibile" : "Funzione non ancora disponibile",
		"titoloStorico" : "STORICO DEI DATI",
		"periodoStorico" : "PERIODO",
		"dispStorico" : "DISPOSITIVO",
		"buttonStorico" : "AGGIORNA",
		"giornoGrafStorico" : "GIORNO",
		"daGrafStorico" : "DAL",
		"aGrafStorico" : "AL",
		"dispGrafStorico" : "DISPOSITIVO",
		"costoGrafStorico" : "Costo",
		"consumoGrafStorico" : "Consumo",
		"oraLabelStorico" : "Ora",
		"giornoLabelStorico" : "Giorno",
		"meseLabelStorico" : "Mese",
		"noGrafStorico" : "NESSUN DATO DISPONIBILE",
		"giornoStorico" : "Giorno",
		"settStorico" : "Settimana",
		"meseStorico" : "Mese",
		"annoStorico" : "Anno",
		"tuttiStorico" : "Totale",
		"datiMancanti" : "Dati storici non completi",
		"altro" : "Altro",
		"titleTotDisp" : "TOTALE DISPOSITIVI",
		"titleAltriDisp" : "ALTRI CONSUMI",
		"titleTotCons" : "CONSUMI TOTALE",
		"labelCodiceUtente" : "CODICE UTENTE ",
		"serieVenduta" : "Energia Immessa in Rete",
		"serieAcquistata" : "Energia Acquistata dalla Rete",
		"serieConsumi" : "Consumi",
		"serieIAC" : "Produzione",
		"costoConsumoAttualeTitleBox" : "INFORMAZIONI RELATIVE AL CONSUMO",
		"costoProduzioneAttualeTitleBox" : "INFORMAZIONI RELATIVE ALLA PRODUZIONE",
		"costoReteAttualeTitleBox" : "INFORMAZIONI RELATIVE ALLA FORNITURA",
		"lblConsO" : "Consumo Odierno",
		"lblProdA" : "Produzione Attuale",
		"lblPotA" : "Potenza Attuale",
		"oldBrowser" : "VERSIONE DEL BROWSER NON ADATTA! Si prega di aggiornare il browser con l'ultima versione."
	},
	community : {
		"titoloForum" : "FORUM ENERGY@HOME",
		"forumMsg" : "Questa e' la sezione del forum Energy@Home. <br>Qui potrai esprimere la tua opinione, fare i tuoi commenti, chiedere informazioni agli altri partecipanti del trial, ricevere suggerimenti ed anche segnalare eventuali criticita' o dubbi sulla sperimentazione. <br>Accedi al forum, registrati e poi inserisci tanti messaggi quanti vuoi su uno o pi� dei 'topic' proposti. <br>Buona sperimentazione!",
		"forumText" : "Clicca qui"
	},
	opzLocal : {
		"titoloForum" : "OPZIONI DI CONFIGURAZIONE LOCALE",
		"forumMsg" : "Qui accedi alla configurazione locale del sistema E@H!"
	},
	trial : {
		"titoloTariffa" : "TARIFFA",
		"tariffaFeriale" : "Feriale",
		"tariffaFestiva" : "Festiva",
		"tariffaBassa" : "Tariffa Bassa",
		"tariffaMedia" : "Tariffa Media",
		"tariffaAlta" : "Tariffa Alta",
		"tariffaOra" : "Ora",
		"titoloInfo" : "INFORMAZIONI",
		"titoloTestoInfo" : "COSA DEVI SAPERE SUL TRIAL",
		"testoInfo" : "Il trial Energy@Home avra' la durata di un anno circa e ti consentira' di controllare i tuoi consumi elettrici.<br><br>Ti suggeriamo di guardare con attenzione le tariffe in uso e di provare a risparmiare, consumando nelle fasce a minor costo.<br><br>Potrai anche confrontare i tuoi consumi con quelli degli altri partecipanti al trial e darci i tuoi suggerimenti andando nella community.",
		"titoloContatti" : "CONTATTI",
		"titoloTestoContatti" : "SE VUOI CONTATTARCI",
		"telNum" : "800 678 477",
		"email" : "energyathome@telecomitalia.it",
		"titoloQuestionari" : "QUESTIONARI",
		"noQuestionari" : "Attualmente non sono presenti questionari"
	},
	report : {
		"report" : "REPORT della SETTIMANA dal ",
		"reportAl" : " al ",
		"TitoloEventiCasa" : "I TUOI CONSUMI :",
		"TitoloElettrodomDettaglio" : "DETTAGLI :",
		"ConsumiFissi" : "Consumi di stand-by ",
		"TempoEldo" : "Tempo medio di accensione ",
		"ConsumoFasciaEco" : "Percentuale di consumo nella fascia economica (F2-3)",
		"PrevisioneSpesaAnnua" : "Previsione di spesa annua",
		"CO2" : "CO2 Prodotta fino ad oggi",
		"IAC" : "Quota di autoconsumo",
		"Eldo" : "Utilizzo ieri : ",
		"ProiezioneAnno" : "Mia Proiezione Anno",
		"Media" : "Media Community",
		"TitoliAccordion" : [[ "Posizione in classifica", "Media Community", "Previsione costo annuo" ], //home
						     [ "Posizione in classifica", "Consumi fascia economica", "Media Community"], //home
						     [ "Media Community", "Consumo di Stand-by", "Costo annuo Stand-by" ], //eldo
						     [ "Posizione in classifica", "Media Community", "Stima costo annuale"], //eldo
						     [ "Posizione in classifica", "Media Community", "Energia auto-consumata" ]], //home
		"carosello" : [ " CASA ", " FORNO ", " FRIGO ", " PC ", " LAMPADA ", " SMART TV ", " LAVATRICE " ],
		"posizione" : ["<img src='./Resources/Images/trofeo_primo_.png' alt='Primo in classifica' title='Bravo sei 1&#176; in classifica continua cos&#237;!' />",
					   "<img src='./Resources/Images/MedagliaArgento_.png' alt='Secondo in classifica' title='Sei 2&#176; in classifica !' />",
		               "<img src='./Resources/Images/MedagliaBronzo_.png' alt='Terzo in classifica' title='Sei 3&#176; in classifica !' />",
		               "<img src='./Resources/Images/cucchiaio_legno_.png' alt='Ultimo in classifica' title='Sei ultimo in classifica' />"],
		"bilancioEnergetico" : ["TFO - Energia immessa in rete", "TPA - Energia consumata in sito", "Energia Prodotta", "Energia Consumata", "Energia Prelevata dalla rete", "% di Auto-consumo", "% di Auto-sufficienza"],
		"informaReport" : [
				"I 'consumi elettrici' fissi (o consumi di stand-by) sono i consumi minimi di casa tua, quelli cioe' che hai anche quando tutto sembra spento (ad esempio gli stand-by di elettrodomestici e dispositivi elettronici)",
				"I consumi di Stand-by si riferiscono ai momenti in cui l'elettrodomestico o il dispositivo elettronico e' acceso ma non utilizzato",
				"I 'consumi in fascia economica' sono i consumi elettrici che hai quando l' energia costa meno (ad esempio nella fascia serale / notturna o nei weekend). <br>Nella tabella a sinistra sono riportati la percentuale di utilizzo dell'elettrodomestico in fascia economica, la tua posizione in classifica nella community e il valor medio della community, la stima di costo annuale dell'energia di questo elettrodomestico.",
				"La 'produzione di CO2' indica gli effetti nocivi di un eccessivo consumo energetico sulla terra ed i suoi abitanti. Approssimativamente si producono 600 g di CO2 per KWh consumato",
				//"Il Quinto Conto Energia incentiva l'autoconsumo dell'energia prodotta dal tuo impianto fotovoltaico. Pertanto i vantaggi economici aumentano con l'aumentare della quota percentuale di autoconsumo.<br/>La tabella sotto riporta il Bilancio Energetico Settimanale della tua abitazione."
				"Il Conto energia e' il nome del programma di incentivazione per la produzione di elettricita' da fonte solare mediante impianti fotovoltaici connessi alla rete elettrica. L'incentivo ha il fine di stimolare l'installazione di impianti fotovoltaici.<br/>La tabella riporta il bilancio energetico settimanale della tua casa."
				 ]
	},
	daysOfWeek : [ "Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom" ],
	mesiAbbrev : [ "Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic" ],
	mesiCompleto : [ "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre" ],
	visErr : [
			"Errore",
			"Errore di connettivita'",
			"Errore di connessione: il server non risponde",
			"Errore: dati mancanti",
			"Attenzione! Il contatore ENEL non e' configurato nel sistema Energy@Home",
			"Identificativo Utente non trovato.",
			"Attenzione! Il contatore di produzione non e' configurato nel sistema Energy@Home"],
	locazioni : {
		"kitchen" : "Cucina",
		"bathroom" : "Bagno",
		"studio" : "Studio",
		"garden" : "Giardino",
		"bedroom" : "Camera da letto",
		"living room" : "Soggiorno",
		"lab" : "Laboratorio",
		"hall" : "Ingresso",
		"corridor" : "Corridoio",
		"other" : "Altro"
	},
	storico : [ "Ora del giorno", "Giorno della settimana", "Giorno del mese", "Mese dell'anno" ],
	titleGraphStorico : [ "Consumi", "Costi", "Produzione" ],
	deviceConsConsumi : [ "ricaricare cellulare o tablet", "accendere PC o TV",
	                      "accendere aspirapolvere o scopa elettrica",
	                      "accendere condizionatore o deumidificatore",
	                      "accendere un grande elettrodomestico (lavastoviglie, lavatrice o forno)" ],
	consigliConsumi : [ "IMPORTANTE ", "Il tuo impianto fotovoltaico ti suggerisce di ", " ora", "", "" ],
	stanze : {
		0 : "Altro",
		1 : "Cucina",
		2 : "Studio",
		3 : "Giardino",
		4 : "Bagno",
		5 : "Camera da letto",
		6 : "Soggiorno",
		7 : "Laboratorio",
		8 : "Ingresso",
		9 : "Corridoio",
		10 : "Presa SmartInfo"
	},
	dispositivi : {
		1 : "Altro",
		2 : "Lampada",
		3 : "Boiler",
		4 : "TV",
		5 : "PC",
		6 : "Forno",
		7 : "Ferro da stiro",
		8 : "Frigorifero",
		9 : "Lavastoviglie",
		10 : "Condizionatore",
		11 : "Lavatrice",
		12 : "Smart Info",
		13 : "Jolly SmartPlug",
		14 : "Contatore fotovoltaico",
		15 : "Contatore secondario",
		16 : "Stampante",
		17 : "Modem/Router",
		18 : "Decoder/Recorder/Player",
		19 : "Home Theatre/Stereo",
		20 : "Play Station",
		21 : "Media Center",
		22 : "Congelatore",
		23 : "Asciugatrice",
		24 : "Aspirapolvere",
		25 : "Phon",
		26 : "Macchina del pane",
		27 : "Macchina del caff�",
		28 : "Tosta pane",
		29 : "Robot cucina",
		30 : "Depuratore acqua",
		31 : "Piano cottura",
		32 : "Stufa elettrica",
		33 : "Pompa piscina"
	}
}
