
package org.energy_home.jemma.ah.cluster.zigbee.closures;

import org.energy_home.jemma.ah.hac.ApplianceException;
import org.energy_home.jemma.ah.hac.IEndPointRequestContext;
import org.energy_home.jemma.ah.hac.ServiceClusterException;


/**
 * This file is part of JEMMA - http://jemma.energy-home.org
 * (C) Copyright 2014 Telecom Italia (http://www.telecomitalia.it)
 * 
 * JEMMA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License (LGPL) version 3
 * or later as published by the Free Software Foundation, which accompanies
 * this distribution and is available at http://www.gnu.org/licenses/lgpl.html
 * 
 * JEMMA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License (LGPL) for more details.
 * 
 * This interface has been generated by the Jemma ZigBee Cluster Library
 * generator, version 2.0.13-SNAPSHOT
 * 
 */
public interface DoorLockClient {

    final static String CMD_OperationEventNotification_NAME = "OperationEventNotification";
    final static String CMD_ProgrammingEventNotification_NAME = "ProgrammingEventNotification";

    public void execOperationEventNotification(short OperationEventSource, short OperationEventCode, int UserID, short PIN, long ZigBeeLocalTime, String Data, IEndPointRequestContext context)
        throws ApplianceException, ServiceClusterException
    ;

    public void execProgrammingEventNotification(short ProgramEventSource, short OperationEventCode, int UserID, short PIN, short UserType, short UserStatus, long ZigBeeLocalTime, String Data, IEndPointRequestContext context)
        throws ApplianceException, ServiceClusterException
    ;

}
